import "./globals.css";

import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
export const metadata = {
  title: "Pits | Webdev",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='de'>
      <body>
        <div className='_app'>
          <Nav />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
